package com.m2018.january.January03;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Create by A-mdx at 2018/1/3 23:19
 */
public class WechatTiao {
    private JPanel tiao;
    private JLabel syso1;
    private JLabel img1;


    public WechatTiao() {
        tiao.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                super.mouseClicked(e);
                int x = e.getX();
                int y = e.getY();
                System.out.println("x:" + x + "  y:" + y);

                ImageIcon icon = new ImageIcon("C:\\Users\\63418\\Desktop\\hehe\\p.jpg");
                icon.setImage(icon.getImage().getScaledInstance(432, 768, Image.SCALE_DEFAULT));
                img1.setIcon(icon);
            }

        });


        ImageIcon icon = new ImageIcon("C:\\Users\\63418\\Desktop\\hehe\\m.png");
        icon.setImage(icon.getImage().getScaledInstance(432, 768, Image.SCALE_DEFAULT));
        img1.setIcon(icon);
        img1.setText("what fuck....");
        img1.setBounds(10, 10, 10, 10);
    }

    public static void main(String[] args) throws InterruptedException {

        WechatTiao wechatTiao = new WechatTiao();

        JFrame frame = new JFrame("WechatTiao");
//        {
//            ImageIcon imageIcon = new ImageIcon("C:\\Users\\63418\\Desktop\\hehe\\m.png");
////            Image image = getToolkit().createImage("C:\\Users\\63418\\Desktop\\hehe\\m.png");
//
//            @Override
//            public void paint(Graphics g) {
//                imageIcon.setImage(imageIcon.getImage().getScaledInstance(540, 960, Image.SCALE_DEFAULT));
////                System.out.println(image2.getWidth(null) + "  " + image2.getHeight(null));
//                getGraphics().drawImage(imageIcon.getImage(), 0, 0, this);
//            }
//        };
        frame.setContentPane(wechatTiao.tiao);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setSize(540, 960);


        frame.setLocationRelativeTo(wechatTiao.tiao);
        wechatTiao.syso1.setText("fuck....");
        frame.setVisible(true);


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tiao = new JPanel();
        tiao.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        img1 = new JLabel();
        img1.setText("Label");
        tiao.add(img1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        syso1 = new JLabel();
        syso1.setText("Label");
        tiao.add(syso1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tiao;
    }
}
