package com.m2018.january.January03;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.Map;

/**
 * Create by A-mdx at 2018/1/3 23:19
 */
public class WechatTiao {
    private JPanel tiao;
    private JLabel syso1;
    private JLabel img1;

    private IndexClick indexClick1;
    private IndexClick indexClick2;


    public WechatTiao() {
        tiao.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                super.mouseClicked(e);
                int x = e.getX();
                int y = e.getY();
                System.out.println("x:" + x + "  y:" + y);
                if (indexClick1 == null) {
                    indexClick1 = new IndexClick(x, y);
                } else {
                    indexClick2 = new IndexClick(x, y);
                    doCal();
                }
//                ImageIcon icon = new ImageIcon("C:\\Users\\63418\\Desktop\\hehe\\p.jpg");
//                icon.setImage(icon.getImage().getScaledInstance(432, 768, Image.SCALE_DEFAULT));
//                img1.setIcon(icon);
            }

        });


        sendShellOrder(screenCap);
        sendShellOrder(pullScreen);
        ImageIcon icon = new ImageIcon("C:\\Users\\63418\\Desktop\\hehe\\1.png");
        icon.setImage(icon.getImage().getScaledInstance(432, 768, Image.SCALE_DEFAULT));
        img1.setIcon(icon);
        img1.setBounds(10, 10, 10, 10);

    }

    private final String pressOrder = "adb shell input touchscreen swipe 170 187 170 187 ";
    private final String screenCap = "adb shell screencap -p /sdcard/mi/1.png";
    private final String pullScreen = "adb pull /sdcard/mi/1.png C:\\Users\\63418\\Desktop\\hehe";

    private void doCal() {
        // 1. 计算距离
        int a = Math.abs(indexClick1.y - indexClick2.y);
        int b = Math.abs(indexClick1.x - indexClick2.y);
        int c = (a + b);
        System.out.println("a:" + a + " - b:" + b);
        System.out.println("开始计算:" + c);
        syso1.setText("开始计算 需要按压时间:" + c);

        // 2. 计算需要按压时间
        int time = (int) (c * 2);

        // 3. 发送按压命令
        sendShellOrder(pressOrder + time);

        try {
            // 跳完才行啊
            Thread.sleep(800);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 4. 截屏+上传保存
        sendShellOrder(screenCap);
        sendShellOrder(pullScreen);

        // 5. 刷新
        ImageIcon icon = new ImageIcon("C:\\Users\\63418\\Desktop\\hehe\\1.png");
        icon.setImage(icon.getImage().getScaledInstance(432, 768, Image.SCALE_DEFAULT));
        img1.setIcon(icon);

        // 6. 清除
        indexClick2 = null;
        indexClick1 = null;

    }

    private static void sendShellOrder(String order) {
        try {
            Process process = Runtime.getRuntime().exec(" C:\\program1\\platform-tools\\" + order);
            process.waitFor();
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tiao = new JPanel();
        tiao.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        img1 = new JLabel();
        img1.setText("Label");
        tiao.add(img1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        syso1 = new JLabel();
        syso1.setText("Label");
        tiao.add(syso1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tiao;
    }

    static class IndexClick {
        int x;
        int y;

        public IndexClick(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }

    public static void main(String[] args) throws InterruptedException {

        WechatTiao wechatTiao = new WechatTiao();

        JFrame frame = new JFrame("WechatTiao");
//        {
//            ImageIcon imageIcon = new ImageIcon("C:\\Users\\63418\\Desktop\\hehe\\m.png");
////            Image image = getToolkit().createImage("C:\\Users\\63418\\Desktop\\hehe\\m.png");
//
//            @Override
//            public void paint(Graphics g) {
//                imageIcon.setImage(imageIcon.getImage().getScaledInstance(540, 960, Image.SCALE_DEFAULT));
////                System.out.println(image2.getWidth(null) + "  " + image2.getHeight(null));
//                getGraphics().drawImage(imageIcon.getImage(), 0, 0, this);
//            }
//        };
        frame.setContentPane(wechatTiao.tiao);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setSize(540, 960);


        frame.setLocationRelativeTo(wechatTiao.tiao);
        wechatTiao.syso1.setText("fuck....");
        frame.setVisible(true);


    }

}
