package com.m2017.august;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

/**
 * Find the Difference
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 * <p>
 * Created by a-mdx on 2017/8/9.
 * https://leetcode.com/problems/find-the-difference/description/
 * 找不同？
 * 作为已经学习过数据结构的，应该可以很快，使用 栈 结构？
 */
public class Aug09 {
    public char findTheDifference(String s, String t) {
        char[] srr = s.toCharArray();
        char[] trr = t.toCharArray();
        List<Character> list = new ArrayList<>();
        for (int i = 0; i < srr.length; i++) {
            list.add(srr[i]);
        }
        for (int i = 0; i < trr.length; i++) {
            Character c = trr[i];
            if (list.contains(c)){
                list.remove(c);
            }else {
                return c;
            }
        }
        return trr[trr.length-1];
    }

    @Test
    public void test1(){
        System.out.println(findTheDifference("qwety","yteewq"));
    }
}
